service: dinesh-serverless

provider:
  name: aws
  runtime: python3.6

functions:
  create:
    handler: create.create
    events:
      - http:
          path: users
          method: post
          cors: true
  fetch:
    handler: fetch.fetch
    events:
      - http:
          path: users/{user_id}
          method: get
          cors: true
          request:
            parameters:
               paths:
                 user_id: true
  delete:
    handler: delete.delete
    events:
      - http:
          path: users/{user_id}
          method: delete
          cors: true
          request:
            parameters:
               paths:
                 user_id: true
  update:
    handler: update.update
    events:
      - http:
          path: users/{user_id}
          method: PUT
          cors: true
          request:
            parameters:
               paths:
                 user_id: true
